### ISSUE TITLE
Add a c++ module for machine learning and run sample

### ISSUE THREAD

**Issue by fire** [V-Sekai/manuals#386]
### Context and Problem Statement

I want to have a starting place for testing ai algorithms.

### Describe the proposed option and how it helps to overcome the problem or limitation

Create a Godot Engine C++ module with a machine learning computation backend.

Find a interesting test case.

Want to run the machine learning technology on the player's computer, the cpu-only server that hosts the game, and the gpu cloud.

To summarize, if you're looking for a sample that demonstrates loading a model at runtime for CPU, Vulkan, and CUDA in C++, you can check out the IREE samples. In particular, the dynamic_shapes and simple_embedding samples showcase how to run on your choice of target. The input program may have a signature in the stablehlo dialect, and you can use IREE or XLA depending on your preferred tech stack or runtime requirements. The Vulkan stack in IREE is relatively stable and offers good performance, with nod.ai's SHARK offering extra tuning and APIs on top. However, there may be differences in optimization depending on the workload and potential driver bugs and pitfalls.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

Provide IREE to godot engine.

Uses the Vulkan back end.

1. input_count
4. input/0/data (TypedArray)
5. output_count
6. output/0/data (TypedArray)

### Positive Consequences

Have a playground for testing.

### Option graveyard

Don't use onnx because it doesn't have vulkan support which limits reach.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Not a small number of gdscript lines.

### Is there a reason why this should be core and done by us?

I know how, and no one else is doing it.

### References

- [V-Sekai](https://v-sekai.org/)
- [SHARK](https://github.com/nod-ai/SHARK)
- IREE in-tree samples: https://github.com/openxla/iree/tree/main/samples
- IREE extra/more complex samples: https://github.com/iree-org/iree-samples
- IREE dynamic shapes sample: https://github.com/openxla/iree/tree/main/samples/dynamic_shapes
- IREE CPU/Vulkan/CUDA sample: https://github.com/openxla/iree/tree/main/samples/simple_embedding
- XLA axpy example: https://github.com/openxla/xla/tree/main/xla/examples/axpy
- nod.ai SHARK: https://github.com/nod-ai/SHARK
- nod.ai SHARK results on AMD GPUs using Vulkan: https://nod.ai/sd-rdna3-ces2023/

**Comment by fire** [comment]
Todo:

1. train a image of digits to label
2. save as a onnx runtime
3. execute via ncnn
4. ???
5. Digits recognized

**Comment by fire** [comment]
```
# config.yaml
input_features:
- name: image_path
  type: image
  encoder: stacked_cnn
  conv_layers:
    - num_filters: 32
      filter_size: 3
      pool_size: 2
      pool_stride: 2
    - num_filters: 64
      filter_size: 3
      pool_size: 2
      pool_stride: 2
      dropout: 0.4
  fc_layers:
    - output_size: 128
      dropout: 0.4

output_features:
 - name: label
   type: category
```

```bat
pip install ludwig
ludwig datasets download mnist
set NUMEXPR_MAX_THREADS=30
ludwig.exe train  --dataset mnist_dataset.csv --config ./config.yaml
```
